/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;
    
import Modelo.*;
import javax.swing.JOptionPane;
import proyectofinal.ProyectoFinal;

/**
 *
 * @author UsueUrruela
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Bienvenida
     */
    private char tipo;
    public Principal() {
        
        initComponents();
       
        
        
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmUsuario = new javax.swing.JMenu();
        jmPerfil = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmVer = new javax.swing.JMenuItem();
        jmInformes = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jmParteNuevo = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        jMenuItem6.setText("jMenuItem6");

        jMenuItem7.setText("jMenuItem7");

        jMenuItem8.setText("jMenuItem8");

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jmUsuario.setText("Usuario");

        jmPerfil.setText("Ver perfil");
        jmPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmPerfilActionPerformed(evt);
            }
        });
        jmUsuario.add(jmPerfil);

        jMenuBar1.add(jmUsuario);

        jMenu2.setText("Administración");

        jmVer.setText("Ver partes");
        jmVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmVerActionPerformed(evt);
            }
        });
        jMenu2.add(jmVer);

        jmInformes.setText("Informes");
        jmInformes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmInformesActionPerformed(evt);
            }
        });
        jMenu2.add(jmInformes);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Logística");
        jMenu3.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu3MenuSelected(evt);
            }
        });
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        jmParteNuevo.setText("Añadir parte");
        jmParteNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmParteNuevoActionPerformed(evt);
            }
        });
        jMenu3.add(jmParteNuevo);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 782, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 431, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmPerfilActionPerformed
        // TODO add your handling code here:
            VentanaTrabajador vt = new VentanaTrabajador();
            vt.setLocationRelativeTo(null);
            vt.setVisible(true);
        
    }//GEN-LAST:event_jmPerfilActionPerformed

    private void jmParteNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmParteNuevoActionPerformed
        // TODO add your handling code here:
        tipo = ProyectoFinal.pedirTipo();
        if(tipo=='a'){
            JOptionPane.showMessageDialog(this, "Solo accesible a trabajadores de logística");
        }else{
            Partes pa = new Partes();
            pa.setLocationRelativeTo(null);
            pa.setVisible(true);
        }
        
        
       
        
    }//GEN-LAST:event_jmParteNuevoActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void jMenu3MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu3MenuSelected
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenu3MenuSelected

    private void jmInformesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmInformesActionPerformed
        // TODO add your handling code here:
        tipo = ProyectoFinal.pedirTipo();
        if(tipo=='l'){
            JOptionPane.showMessageDialog(this, "Solo accesible a trabajadores de administración");
        }else{
            Informes vi = new Informes();
            vi.setVisible(true);
            vi.setLocationRelativeTo(null);
        }
    }//GEN-LAST:event_jmInformesActionPerformed

    private void jmVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmVerActionPerformed
        // TODO add your handling code here:
        tipo = ProyectoFinal.pedirTipo();
        if(tipo=='l'){
            JOptionPane.showMessageDialog(this, "Solo accesible a trabajadores de administración");
        }else{
            VerPartes vp = new VerPartes();
            vp.setLocationRelativeTo(null);
            vp.setVisible(true);
        }

    }//GEN-LAST:event_jmVerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JMenuItem jmInformes;
    private javax.swing.JMenuItem jmParteNuevo;
    private javax.swing.JMenuItem jmPerfil;
    private javax.swing.JMenu jmUsuario;
    private javax.swing.JMenuItem jmVer;
    // End of variables declaration//GEN-END:variables
}
